import { theme } from "@/lib/theme";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: theme.canvas,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    gap: 18,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    backgroundColor: theme.canvas,
  },
  loadingText: {
    color: theme.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  hero: {
    gap: 18,
    padding: 20,
    borderRadius: 32,
    borderCurve: "continuous",
    backgroundColor: theme.inkInverted,
    borderWidth: 1,
    borderColor: theme.parchmentLight,
    overflow: "hidden",
  },
  heroContent: {
    gap: 18,
  },

  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logoMark: {
    width: 42,
    height: 42,
    borderRadius: 16,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.accent,
  },
  brand: {
    color: theme.ink,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  drop: {
    color: theme.inkAlpha50,
    fontSize: 13,
    fontWeight: "800",
  },
  headline: {
    color: theme.ink,
    fontSize: 42,
    lineHeight: 44,
    fontWeight: "900",
    letterSpacing: -1.7,
  },
  subhead: {
    color: theme.inkAlpha72,
    fontSize: 16,
    lineHeight: 23,
    fontWeight: "700",
  },
  primaryButton: {
    minHeight: 54,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: theme.accent,
  },
  primaryButtonText: {
    color: theme.inkOnAccent,
    fontSize: 16,
    fontWeight: "900",
  },
  introActions: {
    gap: 10,
  },
  secondaryIntroButton: {
    minHeight: 52,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: theme.inkAlpha8,
    borderWidth: 1,
    borderColor: theme.inkAlpha13,
  },
  secondaryIntroButtonText: {
    color: theme.ink,
    fontSize: 16,
    fontWeight: "900",
  },
  scoreStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },

  actionBar: {
    flexDirection: "row",
    gap: 10,
  },
  actionButton: {
    minHeight: 52,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 18,
    borderCurve: "continuous",
  },
  guessButton: {
    flex: 1,
    backgroundColor: theme.accent,
  },
  guessButtonText: {
    color: theme.inkOnAccent,
    fontSize: 14,
    fontWeight: "900",
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: theme.inkAlpha8,
    borderWidth: 1,
    borderColor: theme.inkAlpha12,
  },
  secondaryButtonText: {
    color: theme.ink,
    fontSize: 14,
    fontWeight: "900",
  },
  disabledButton: {
    opacity: 0.45,
  },
  pressed: {
    opacity: 0.72,
  },
  sceneRail: {
    flexDirection: "row",
    gap: 10,
  },
  scenePill: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: theme.inkAlpha8,
    borderWidth: 1,
    borderColor: theme.inkAlpha10,
  },
  scenePillActive: {
    backgroundColor: theme.accent,
  },
  scenePillText: {
    color: theme.inkAlpha72,
    fontSize: 16,
    fontWeight: "900",
  },
  scenePillTextActive: {
    color: theme.inkOnAccent,
  },
  ritualCard: {
    padding: 18,
    gap: 10,
    borderRadius: 24,
    borderCurve: "continuous",
    backgroundColor: theme.accentMutedBg,
    borderWidth: 1,
    borderColor: theme.accentMutedBorder,
  },
  ritualHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ritualTitle: {
    color: theme.accent,
    fontSize: 16,
    fontWeight: "900",
  },
  ritualText: {
    color: theme.inkAlpha68,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "700",
  },
  stepBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 3,
    paddingHorizontal: 7,
    borderRadius: 999,
    backgroundColor: theme.inkAlpha4,
  },
  stepBadgeLabel: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  venicePipelineCard: {
    padding: 16,
    gap: 12,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: theme.violetMuted,
    borderWidth: 1,
    borderColor: theme.violetBorder,
  },
  venicePipelineHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  venicePipelineIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.violetIconBg,
  },
  venicePipelineInfo: {
    flex: 1,
    gap: 2,
  },
  venicePipelineTitle: {
    color: theme.ink,
    fontSize: 15,
    fontWeight: "900",
  },
  venicePipelineSub: {
    color: theme.inkAlpha40,
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 15,
  },
  venicePipelineSteps: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  venicePipelineAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 14,
    borderCurve: "continuous",
    backgroundColor: theme.violet,
  },
  venicePipelineActionText: {
    color: theme.inkOnAccent,
    fontSize: 13,
    fontWeight: "900",
  },
  curatorLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 12,
    marginTop: 8,
  },
  onChainRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  curatorLinkText: {
    color: theme.neutralDark,
    fontSize: 12,
    fontWeight: "500",
  },
  lastSolveCard: {
    padding: 16,
    gap: 10,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: theme.accentAlpha6,
    borderWidth: 1,
    borderColor: theme.accentSoft,
  },
  lastSolveHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  lastSolveTitle: {
    flex: 1,
    color: theme.accent,
    fontSize: 13,
    fontWeight: "900",
  },
  lastSolveDismiss: {
    padding: 4,
  },
  lastSolveFigure: {
    color: theme.ink,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  lastSolveStats: {
    flexDirection: "row",
    gap: 16,
  },
  lastSolveStat: {
    gap: 2,
  },
  lastSolveStatValue: {
    color: theme.ink,
    fontSize: 18,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  lastSolveStatLabel: {
    color: theme.inkAlpha40,
    fontSize: 11,
    fontWeight: "700",
  },
  historyCard: {
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: theme.inkAlpha3,
    borderWidth: 1,
    borderColor: theme.inkAlpha6,
    overflow: "hidden",
  },
  historyToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 16,
  },
  historyTitle: {
    flex: 1,
    color: theme.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  historyList: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderCurve: "continuous",
    backgroundColor: theme.inkAlpha3,
  },
  historyRowLeft: {
    flex: 1,
    gap: 2,
  },
  historyFigure: {
    color: theme.ink,
    fontSize: 14,
    fontWeight: "900",
  },
  historyDate: {
    color: theme.inkAlpha35,
    fontSize: 11,
    fontWeight: "600",
  },
  historyRowRight: {
    alignItems: "flex-end",
    gap: 2,
  },
  historyScore: {
    color: theme.accent,
    fontSize: 15,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  historyMeta: {
    color: theme.inkAlpha35,
    fontSize: 11,
    fontWeight: "600",
  },
  historyExhausted: {
    color: theme.dangerText,
    fontSize: 12,
    fontWeight: "700",
  },
  brandTextCol: {
    flex: 1,
  },
  archiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: theme.accentAlpha12,
    borderWidth: 1,
    borderColor: theme.accentMutedBorder,
  },
  archiveBadgeText: {
    color: theme.ink,
    fontSize: 12,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  suggestionsCard: {
    padding: 14,
    gap: 10,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: theme.violetMuted,
    borderWidth: 1,
    borderColor: theme.violetIconBg,
  },
  suggestionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  suggestionText: {
    color: theme.inkAlpha70,
    fontSize: 13,
    fontWeight: "700",
  },
  nextActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  nextActionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderCurve: "continuous",
    backgroundColor: theme.inkAlpha6,
    borderWidth: 1,
    borderColor: theme.inkAlpha10,
  },
  nextActionText: {
    color: theme.ink,
    fontSize: 12,
    fontWeight: "800",
  },
  exhaustedCard: {
    padding: 18,
    gap: 12,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: theme.dangerBg,
    borderWidth: 1,
    borderColor: theme.dangerBorder,
  },
  exhaustedTitle: {
    color: theme.dangerMuted,
    fontSize: 16,
    fontWeight: "900",
  },
  exhaustedSub: {
    color: theme.inkAlpha55,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
});
