import { StyleSheet } from "react-native";

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#070A12",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    gap: 18,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    backgroundColor: "#070A12",
  },
  loadingText: {
    color: "#FFF7ED",
    fontSize: 16,
    fontWeight: "800",
  },
  hero: {
    gap: 18,
    padding: 20,
    borderRadius: 32,
    borderCurve: "continuous",
    backgroundColor: "#1C1106",
    borderWidth: 1,
    borderColor: "rgba(248, 231, 201, 0.13)",
    overflow: "hidden",
  },
  heroContent: {
    gap: 18,
  },

  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logoMark: {
    width: 42,
    height: 42,
    borderRadius: 16,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FBBF24",
  },
  brand: {
    color: "#FFF7ED",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  drop: {
    color: "rgba(255, 247, 237, 0.5)",
    fontSize: 13,
    fontWeight: "800",
  },
  headline: {
    color: "#FFF7ED",
    fontSize: 42,
    lineHeight: 44,
    fontWeight: "900",
    letterSpacing: -1.7,
  },
  subhead: {
    color: "rgba(255, 247, 237, 0.72)",
    fontSize: 16,
    lineHeight: 23,
    fontWeight: "700",
  },
  primaryButton: {
    minHeight: 54,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "#FBBF24",
  },
  primaryButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "900",
  },
  introActions: {
    gap: 10,
  },
  secondaryIntroButton: {
    minHeight: 52,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "rgba(255, 247, 237, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 247, 237, 0.13)",
  },
  secondaryIntroButtonText: {
    color: "#FFF7ED",
    fontSize: 16,
    fontWeight: "900",
  },
  scoreStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },

  actionBar: {
    flexDirection: "row",
    gap: 10,
  },
  actionButton: {
    minHeight: 52,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 18,
    borderCurve: "continuous",
  },
  guessButton: {
    flex: 1,
    backgroundColor: "#FBBF24",
  },
  guessButtonText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: "rgba(255, 247, 237, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 247, 237, 0.12)",
  },
  secondaryButtonText: {
    color: "#FFF7ED",
    fontSize: 14,
    fontWeight: "900",
  },
  disabledButton: {
    opacity: 0.45,
  },
  pressed: {
    opacity: 0.72,
  },
  sceneRail: {
    flexDirection: "row",
    gap: 10,
  },
  scenePill: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(255, 247, 237, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 247, 237, 0.1)",
  },
  scenePillActive: {
    backgroundColor: "#FBBF24",
  },
  scenePillText: {
    color: "rgba(255, 247, 237, 0.72)",
    fontSize: 16,
    fontWeight: "900",
  },
  scenePillTextActive: {
    color: "#111827",
  },
  ritualCard: {
    padding: 18,
    gap: 10,
    borderRadius: 24,
    borderCurve: "continuous",
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.2)",
  },
  ritualHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ritualTitle: {
    color: "#FBBF24",
    fontSize: 16,
    fontWeight: "900",
  },
  ritualText: {
    color: "rgba(255, 247, 237, 0.68)",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "700",
  },
  stepBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 3,
    paddingHorizontal: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255, 247, 237, 0.04)",
  },
  stepBadgeLabel: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  venicePipelineCard: {
    padding: 16,
    gap: 12,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: "rgba(167, 139, 250, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(167, 139, 250, 0.15)",
  },
  venicePipelineHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  venicePipelineIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(167, 139, 250, 0.12)",
  },
  venicePipelineInfo: {
    flex: 1,
    gap: 2,
  },
  venicePipelineTitle: {
    color: "#FFF7ED",
    fontSize: 15,
    fontWeight: "900",
  },
  venicePipelineSub: {
    color: "rgba(255, 247, 237, 0.4)",
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 15,
  },
  venicePipelineSteps: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  venicePipelineAction: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 14,
    borderCurve: "continuous",
    backgroundColor: "#A78BFA",
  },
  venicePipelineActionText: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "900",
  },
  curatorLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 12,
    marginTop: 8,
  },
  onChainRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  curatorLinkText: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "500",
  },
  lastSolveCard: {
    padding: 16,
    gap: 10,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: "rgba(251, 191, 36, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.15)",
  },
  lastSolveHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  lastSolveTitle: {
    flex: 1,
    color: "#FBBF24",
    fontSize: 13,
    fontWeight: "900",
  },
  lastSolveDismiss: {
    padding: 4,
  },
  lastSolveFigure: {
    color: "#FFF7ED",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  lastSolveStats: {
    flexDirection: "row",
    gap: 16,
  },
  lastSolveStat: {
    gap: 2,
  },
  lastSolveStatValue: {
    color: "#FFF7ED",
    fontSize: 18,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  lastSolveStatLabel: {
    color: "rgba(255, 247, 237, 0.4)",
    fontSize: 11,
    fontWeight: "700",
  },
  historyCard: {
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: "rgba(255, 247, 237, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 247, 237, 0.06)",
    overflow: "hidden",
  },
  historyToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 16,
  },
  historyTitle: {
    flex: 1,
    color: "#FFF7ED",
    fontSize: 13,
    fontWeight: "900",
  },
  historyList: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderCurve: "continuous",
    backgroundColor: "rgba(255, 247, 237, 0.03)",
  },
  historyRowLeft: {
    flex: 1,
    gap: 2,
  },
  historyFigure: {
    color: "#FFF7ED",
    fontSize: 14,
    fontWeight: "900",
  },
  historyDate: {
    color: "rgba(255, 247, 237, 0.35)",
    fontSize: 11,
    fontWeight: "600",
  },
  historyRowRight: {
    alignItems: "flex-end",
    gap: 2,
  },
  historyScore: {
    color: "#FBBF24",
    fontSize: 15,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  historyMeta: {
    color: "rgba(255, 247, 237, 0.35)",
    fontSize: 11,
    fontWeight: "600",
  },
  historyExhausted: {
    color: "rgba(239, 68, 68, 0.6)",
    fontSize: 12,
    fontWeight: "700",
  },
  brandTextCol: {
    flex: 1,
  },
  archiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(251, 191, 36, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.2)",
  },
  archiveBadgeText: {
    color: "#FFF7ED",
    fontSize: 12,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  suggestionsCard: {
    padding: 14,
    gap: 10,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(167, 139, 250, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(167, 139, 250, 0.12)",
  },
  suggestionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  suggestionText: {
    color: "rgba(255, 247, 237, 0.7)",
    fontSize: 13,
    fontWeight: "700",
  },
  nextActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  nextActionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderCurve: "continuous",
    backgroundColor: "rgba(255, 247, 237, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(255, 247, 237, 0.1)",
  },
  nextActionText: {
    color: "#FFF7ED",
    fontSize: 12,
    fontWeight: "800",
  },
  exhaustedCard: {
    padding: 18,
    gap: 12,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: "rgba(239, 68, 68, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.15)",
  },
  exhaustedTitle: {
    color: "#FCA5A5",
    fontSize: 16,
    fontWeight: "900",
  },
  exhaustedSub: {
    color: "rgba(255, 247, 237, 0.55)",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
});
