import { Ionicons } from "@expo/vector-icons";
import { StyleSheet, Text, View } from "react-native";

interface VeniceAiBadgeProps {
  type?: "hint" | "scene" | "image";
  compact?: boolean;
}

const TYPE_CONFIG = {
  hint: { icon: "sparkles" as const, label: "Socratic hint via Venice AI" },
  scene: { icon: "image" as const, label: "Scene generated by Venice AI" },
  image: { icon: "color-palette" as const, label: "Image via Venice AI" },
};

export function VeniceAiBadge({ type = "hint", compact = false }: VeniceAiBadgeProps) {
  const config = TYPE_CONFIG[type];

  return (
    <View style={[styles.badge, compact && styles.compact]}>
      <Ionicons name={config.icon} size={compact ? 10 : 12} color="#A78BFA" />
      <Text style={[styles.label, compact && styles.labelCompact]}>{config.label}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: "rgba(167, 139, 250, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(167, 139, 250, 0.2)",
    alignSelf: "flex-start",
  },
  compact: {
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  label: {
    color: "#A78BFA",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  labelCompact: {
    fontSize: 9,
  },
});
